### ISSUE TITLE
翻译功能开关/降低翻译功能优先级

### ISSUE THREAD

**Issue by WindraiteLesd** [zlh-debug/paimon-plugin#2]
PM翻译功能指令与古手梨花的tts插件冲突了
输入#tts关键词会触发本插件的翻译功能导致tts插件被阻断
锅巴的功能黑名单对pm翻译功能不起作用
或者可以更改一下触发方式

**Comment by zlh-debug** [comment]
改成#TTS可以吗，或者优先级降到多少合适

**Comment by WindraiteLesd** [comment]
实际优先级这个我也拿不准，那边的优先级甚至拉到了5w但还是被这个翻译的100给阻断了，是不是有上限啊

**Comment by zlh-debug** [comment]
数字越大，优先级越低。那我改成#PMTTS吧

**Comment by WindraiteLesd** [comment]
忘了优先级遍历是升序了（
那就先改成#PMTTS试试
